import type { CompetitorMatrix, MarketEvidence } from "../market/MarketAgent.js";
import type { InjectedToolResult } from "../../tools/toolTypes.js";

function shortText(value: string, max = 220): string {
  return value.length <= max ? value : `${value.slice(0, max - 1)}...`;
}

export function renderMarketingGtmMarkdown(args: {
  taskText: string;
  contextText: string;
  evidence: MarketEvidence;
  competitorMatrix: CompetitorMatrix;
  results: InjectedToolResult[];
}): string {
  const fulfilled = args.results.filter((r) => r.status === "fulfilled");
  const gaps = args.results.filter((r) => r.status !== "fulfilled" || r.reason);
  const evidenceRows = args.evidence.claims.length
    ? args.evidence.claims.slice(0, 10).map((claim) =>
      `| ${shortText(claim.claim, 80)} | ${shortText(claim.evidence, 120)} | ${claim.sourceUrl ?? "n/a"} | ${claim.confidence} |`
    )
    : ["| No fulfilled external market evidence | Use stated assumptions and conservative estimates | n/a | low |"];
  const competitorRows = args.competitorMatrix.competitors.length
    ? args.competitorMatrix.competitors.map((c) =>
      `| ${c.url} | ${c.detectedPrices.join(", ") || "Not detected"} | ${c.salesMotion ?? "Not detected"} | ${c.confidence} |`
    )
    : ["| No competitor pages fetched | n/a | n/a | low |"];
  const dataGapLines = gaps.length
    ? gaps.map((gap) => `- ${gap.tool}: ${gap.status}${gap.reason ? ` (${gap.reason})` : ""}`)
    : ["- No external data gaps reported by tool injection."];

  return [
    "# Go-to-Market Strategy",
    "",
    "Generated by the CoAgent marketing runtime from concurrent market evidence injection. This native artifact follows the same gtm.md contract used by the Presentation and Finance agents.",
    "",
    "## Target audience & segmentation",
    "",
    "- Primary segment: buyers implied by the PRD/task context.",
    "- Secondary segment: adjacent teams or organizations with similar urgency, budget, and workflow pain.",
    "- Segmentation confidence is medium when external evidence exists, low when tool injection returned no market evidence.",
    "",
    "## Positioning statement & key messages",
    "",
    `For the initiative described as "${shortText(args.taskText, 180)}", position around the clearest measurable customer pain, speed to value, and reduced execution risk.`,
    "",
    "- Message 1: measurable business outcome",
    "- Message 2: faster adoption with lower operational burden",
    "- Message 3: credible differentiation against detected alternatives",
    "",
    "## Channel strategy",
    "",
    "| Priority | Channel | Rationale | Confidence |",
    "| --- | --- | --- | --- |",
    `| 1 | Founder/owned content and direct outreach | Lowest dependency on paid CAC while evidence is still forming | ${fulfilled.length ? "medium" : "low"} |`,
    `| 2 | Search/social testing | Validate problem keywords and audience resonance before scaling spend | ${fulfilled.some((r) => r.tool === "web_search") ? "medium" : "low"} |`,
    "| 3 | Partner/community channels | Useful if target users cluster around existing professional communities | low |",
    "",
    "## Launch timeline",
    "",
    "- Pre-launch: validate ICP, pricing sensitivity, and top objections.",
    "- Launch: publish positioning, run focused outbound, and test 2-3 paid/organic acquisition loops.",
    "- Post-launch: double down on channels with measurable CAC/payback signal.",
    "",
    "## Budget estimate by channel",
    "",
    "| Line | Y1 estimate | Source | Confidence |",
    "| --- | ---: | --- | --- |",
    "| Content / owned media | TBD | estimate | low |",
    "| Paid tests | TBD | estimate | low |",
    "| Sales enablement / launch assets | TBD | estimate | low |",
    "",
    "## Success metrics",
    "",
    "- CAC by channel",
    "- Visitor-to-lead conversion",
    "- Lead-to-customer conversion",
    "- Payback period",
    "- Retention / expansion proxy after launch",
    "",
    "## Market evidence used",
    "",
    "| Claim | Evidence | Source | Confidence |",
    "| --- | --- | --- | --- |",
    ...evidenceRows,
    "",
    "## Competitor matrix",
    "",
    "| Competitor URL | Detected prices | Sales motion | Confidence |",
    "| --- | --- | --- | --- |",
    ...competitorRows,
    "",
    "## Data gaps",
    "",
    ...dataGapLines,
    "",
    "## Data confidence",
    "",
    `- Fulfilled tools: ${fulfilled.map((r) => r.tool).join(", ") || "none"}`,
    `- Overall confidence: ${fulfilled.length >= 2 ? "medium" : "low"}`,
    "- Missing external data is not treated as zero; it remains a human-review gap.",
    "",
    "## Fairness Review",
    "",
    "- Demographic coverage: No demographic exclusions are recommended without human-provided business rationale.",
    "- Channel accessibility: Use accessible landing pages, captions, alt text, and readable campaign creative.",
    "- Message bias: Avoid lifestyle or background assumptions until validated by user research.",
    "- Data sourcing: External data, when available, is listed above; otherwise assumptions are explicitly marked.",
    "- Underserved markets: Treat underserved segments as discovery candidates rather than excluding them by default.",
    "",
    "## Finance-ready data",
    "",
    "| Field | Value | Source | Notes |",
    "| --- | --- | --- | --- |",
    "| Quarters covered | Y1 / 4 quarters | assumption | Update when launch plan is fixed |",
    "| Blended CAC target (Y1) | TBD | assumption | Finance should model conservative/base/optimistic ranges |",
    "| Total paid/performance spend (Y1) | TBD | assumption | Do not treat as approved budget |",
    "| Data revision: v1 | Generated by native marketing runtime | system | Increment if Marketing revises numbers |",
    "",
  ].join("\n");
}
