import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { runToolInjection } from "../tools/toolInjectionRunner.js";

const OLD_ENV = { ...process.env };

afterEach(() => {
  process.env = { ...OLD_ENV };
});

function makeFolder(): string {
  const folder = fs.mkdtempSync(path.join(os.tmpdir(), "coagent-tool-injection-"));
  fs.mkdirSync(path.join(folder, "CoAgent_workspace", "_shared", "artifacts", "market"), { recursive: true });
  fs.mkdirSync(path.join(folder, "CoAgent_workspace", "_shared", "artifacts", "finance"), { recursive: true });
  fs.writeFileSync(path.join(folder, "CoAgent_workspace", "_shared", "scratchpad.jsonl"), "");
  return folder;
}

function makeSessionDir(folder: string, name: string): string {
  const dir = path.join(folder, "CoAgent_workspace", "sessions", name);
  fs.mkdirSync(path.join(dir, "artifacts"), { recursive: true });
  return dir;
}

describe("runToolInjection", () => {
  it("skips all disabled market tools without blocking artifact generation", async () => {
    const folder = makeFolder();
    process.env.COAGENT_DOMAIN_AGENTS = "hybrid";
    process.env.COAGENT_DISABLED_TOOLS = "web_search,competitor_page_fetch,world_bank_indicator";

    const results = await runToolInjection({
      folderPath: folder,
      target: "market",
      taskText: "Build a GTM plan",
    });

    expect(results).toHaveLength(3);
    expect(results.every((r) => r.status === "skipped")).toBe(true);
    const shared = path.join(folder, "CoAgent_workspace", "_shared");
    expect(fs.existsSync(path.join(shared, "artifacts", "market", "tool-injection-results.json"))).toBe(true);
    expect(fs.existsSync(path.join(shared, "artifacts", "market", "market-evidence.json"))).toBe(true);
    expect(fs.readFileSync(path.join(shared, "source-ledger.jsonl"), "utf-8").trim().split("\n")).toHaveLength(3);
    expect(fs.readFileSync(path.join(shared, "artifacts.jsonl"), "utf-8")).toContain("Market evidence");
  });

  it("generates finance injection artifacts when finance tools are disabled or unavailable", async () => {
    const folder = makeFolder();
    const sessionDir = makeSessionDir(folder, "finance");
    process.env.COAGENT_DOMAIN_AGENTS = "hybrid";
    process.env.COAGENT_DISABLED_TOOLS = "exchange_rate,fred_series,world_bank_indicator,sec_edgar_company_facts,alpha_vantage";

    const results = await runToolInjection({
      folderPath: folder,
      target: "finance",
      taskText: "Financial model for $ABCD with CIK 0000320193",
      sessionDir,
    });

    expect(results).toHaveLength(5);
    expect(results.every((r) => r.status === "skipped")).toBe(true);
    const shared = path.join(folder, "CoAgent_workspace", "_shared");
    const financeDataPath = path.join(shared, "artifacts", "finance", "external-finance-data.json");
    expect(fs.existsSync(financeDataPath)).toBe(true);
    const financeData = JSON.parse(fs.readFileSync(financeDataPath, "utf-8"));
    expect(financeData.modelSeed.scenarios.base.confidence).toBe("medium");
    expect(fs.existsSync(path.join(sessionDir, "artifacts", "financial-model.json"))).toBe(true);
    expect(fs.existsSync(path.join(sessionDir, "artifacts", "assumptions.yaml"))).toBe(true);
    expect(fs.existsSync(path.join(sessionDir, "artifacts", "sensitivity-analysis.json"))).toBe(true);
    expect(fs.existsSync(path.join(sessionDir, "artifacts", "financial-model.md"))).toBe(false);
  });

  it("writes native finance markdown only in native mode", async () => {
    const folder = makeFolder();
    const sessionDir = makeSessionDir(folder, "finance");
    process.env.COAGENT_DOMAIN_AGENTS = "native";
    process.env.COAGENT_DISABLED_TOOLS = "exchange_rate,fred_series,world_bank_indicator,sec_edgar_company_facts,alpha_vantage";

    await runToolInjection({
      folderPath: folder,
      target: "finance",
      taskText: "Financial model for $ABCD. Engineering development $100,000. Marketing spend $50,000. CAC $200. LTV $1,000. Infrastructure $2,000.",
      sessionDir,
    });

    const markdownPath = path.join(sessionDir, "artifacts", "financial-model.md");
    const modelPath = path.join(sessionDir, "artifacts", "financial-model.json");
    expect(fs.existsSync(markdownPath)).toBe(true);
    expect(fs.readFileSync(markdownPath, "utf-8")).toContain("Generated by the CoAgent finance runtime");
    const model = JSON.parse(fs.readFileSync(modelPath, "utf-8"));
    expect(model.scenarios.base.developmentCostUsd).toBe(100000);
    expect(model.scenarios.base.marketingSpendUsd).toBe(50000);
    expect(model.scenarios.base.cacUsd).toBe(200);
    expect(model.scenarios.base.ltvUsd).toBe(1000);
    const scratchpad = fs.readFileSync(path.join(folder, "CoAgent_workspace", "_shared", "scratchpad.jsonl"), "utf-8");
    expect(scratchpad).toContain("Done: native financial model");
  });

  it("mirrors market supplemental artifacts into the marketing session", async () => {
    const folder = makeFolder();
    const sessionDir = makeSessionDir(folder, "marketing");
    process.env.COAGENT_DOMAIN_AGENTS = "hybrid";
    process.env.COAGENT_DISABLED_TOOLS = "web_search,competitor_page_fetch,world_bank_indicator";

    await runToolInjection({
      folderPath: folder,
      target: "market",
      taskText: "Create GTM for a B2B SaaS analytics product",
      sessionDir,
    });

    expect(fs.existsSync(path.join(sessionDir, "artifacts", "market-evidence.json"))).toBe(true);
    expect(fs.existsSync(path.join(sessionDir, "artifacts", "competitor-matrix.json"))).toBe(true);
    expect(fs.existsSync(path.join(sessionDir, "artifacts", "market-research.md"))).toBe(true);
    expect(fs.existsSync(path.join(sessionDir, "artifacts", "gtm.md"))).toBe(false);
  });

  it("writes native marketing gtm markdown and compatible handoffs in native mode", async () => {
    const folder = makeFolder();
    const sessionDir = makeSessionDir(folder, "marketing");
    process.env.COAGENT_DOMAIN_AGENTS = "native";
    process.env.COAGENT_DISABLED_TOOLS = "web_search,competitor_page_fetch,world_bank_indicator";

    await runToolInjection({
      folderPath: folder,
      target: "market",
      taskText: "Create GTM for a B2B SaaS analytics product",
      sessionDir,
    });

    const gtmPath = path.join(sessionDir, "artifacts", "gtm.md");
    expect(fs.existsSync(gtmPath)).toBe(true);
    const gtm = fs.readFileSync(gtmPath, "utf-8");
    expect(gtm).toContain("## Market evidence used");
    expect(gtm).toContain("## Finance-ready data");
    const scratchpad = fs.readFileSync(path.join(folder, "CoAgent_workspace", "_shared", "scratchpad.jsonl"), "utf-8");
    expect(scratchpad).toContain("Done: native GTM");
    expect(scratchpad).toContain("Native GTM and budget assumptions ready");
  });

  it("does nothing in legacy mode", async () => {
    const folder = makeFolder();
    process.env.COAGENT_DOMAIN_AGENTS = "legacy";

    const results = await runToolInjection({
      folderPath: folder,
      target: "finance",
      taskText: "Create financial model",
    });

    expect(results).toEqual([]);
  });
});
